<?php

namespace Gbl\BackOfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
	public function findAllOrderByNom()
	{
		return $this->getEntityManager()
		->createQuery('SELECT c FROM GblBackOfficeBundle:Categorie c ORDER BY c.nom')
		->getResult();
	}
	
	public function findAllGroupBy()
	{
		return $this->getEntityManager()
		->createQuery('SELECT c FROM GblBackOfficeBundle:Categorie c GROUP BY c.nom')
		->getResult();
	}
}
