<?php

namespace Gbl\BackOfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends EntityRepository
{
	public function findByNom()
	{
		return $this->getEntityManager()
		->createQuery('SELECT c FROM GblBackOfficeBundle:Categorie c ORDER BY c.nom, c.poids')
		->getResult();
	}
}
