<?php

namespace Gbl\BackOfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
	public function findAllWithStock()
	{
		return $this->getEntityManager()
		->createQuery('SELECT p FROM GblBackOfficeBundle:Produit p WHERE p.stock > 0')
		->getResult();
	}
	
	public function findAllNotStock()
	{
		return $this->getEntityManager()
		->createQuery('SELECT p FROM GblBackOfficeBundle:Produit p WHERE p.stock <= 0')
		->getResult();
	}
	
	public function findAllWithVenteFlashAndWithStock()
	{
		return $this->getEntityManager()
		->createQuery('SELECT p FROM GblBackOfficeBundle:Produit p WHERE p.venteFlash = true AND p.stock > 0')
		->getResult();
	}
	
	public function findAllWithVenteFlashAndNotStock()
	{
		return $this->getEntityManager()
		->createQuery('SELECT p FROM GblBackOfficeBundle:Produit p WHERE p.venteFlash = true AND p.stock <= 0')
		->getResult();
	}
	
}
