<?php

namespace Gbl\BackOfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
	public function findAllNotExpired()
	{
		return $this->getEntityManager()
		->createQuery('SELECT pt FROM GblBackOfficeBundle:Promotion pt WHERE pt.dateFin > CURRENT_DATE()')
		->getResult();
	}
	
	public function findAllExpired()
	{
		return $this->getEntityManager()
		->createQuery('SELECT pt FROM GblBackOfficeBundle:Promotion pt WHERE pt.dateFin < CURRENT_DATE()')
		->getResult();
	}
}
