gbl_back_office:
    resource: "@GblBackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

#FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

#USER 
user.index:
    pattern:  /user/new
    defaults: { _controller: GblBackOfficeBundle:User:index }
 
user.new:
    pattern:  /user/new
    defaults: { _controller: GblBackOfficeBundle:User:new }
    
user.edit:
    pattern:  /user/edit/{id}
    defaults: { _controller: GblBackOfficeBundle:User:edit }
    
user.delete:
    pattern:  /user/delete/{id}
    defaults: { _controller: GblBackOfficeBundle:User:delete }