users : 
  type: rest
  resource:  "GblBackOfficeBundle:UserRest"
  name_prefix:  api_
  
produits:
    type:     rest
    resource: "GblBackOfficeBundle:ProduitRest"
    name_prefix:  api_
    
categories:
    type: rest
    resource: "GblBackOfficeBundle:CategorieRest"
    name_prefix: api_
    
commandes:
    type: rest
    resource: "GblBackOfficeBundle:CommandeRest"
    name_prefix: api_

themes:
    type: rest
    resource: "GblBackOfficeBundle:ThemeRest"
    name_prefix: api_

transporteurs:
    type: rest
    resource: "GblBackOfficeBundle:TransporteurRest"
    name_prefix: api_
    
configurations:
    type: rest
    resource: "GblBackOfficeBundle:ConfigurationRest"
    name_prefix: api_