users : 
  type: rest
  resource:  "GblBackOfficeBundle:UserRest"
  name_prefix:  api_
  
produits:
    type:     rest
    resource: "GblBackOfficeBundle:ProduitRest"
    name_prefix:  api_
    
categories:
    type: rest
    resource: "GblBackOfficeBundle:CategorieRest"
    name_prefix: api_
    
commandes:
    type: rest
    parent: users
    resource: "GblBackOfficeBundle:CommandeRest"
    name_prefix: api_